// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteIpamIPOKCode is the HTTP code returned for type DeleteIpamIPOK
const DeleteIpamIPOKCode int = 200

/*
DeleteIpamIPOK IP address released

swagger:response deleteIpamIpOK
*/
type DeleteIpamIPOK struct {
}

// NewDeleteIpamIPOK creates DeleteIpamIPOK with default headers values
func NewDeleteIpamIPOK() *DeleteIpamIPOK {

	return &DeleteIpamIPOK{}
}

// WriteResponse to the client
func (o *DeleteIpamIPOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteIpamIPBadRequestCode is the HTTP code returned for type DeleteIpamIPBadRequest
const DeleteIpamIPBadRequestCode int = 400

/*
DeleteIpamIPBadRequest Invalid IP address

swagger:response deleteIpamIpBadRequest
*/
type DeleteIpamIPBadRequest struct {
}

// NewDeleteIpamIPBadRequest creates DeleteIpamIPBadRequest with default headers values
func NewDeleteIpamIPBadRequest() *DeleteIpamIPBadRequest {

	return &DeleteIpamIPBadRequest{}
}

// WriteResponse to the client
func (o *DeleteIpamIPBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteIpamIPNotFoundCode is the HTTP code returned for type DeleteIpamIPNotFound
const DeleteIpamIPNotFoundCode int = 404

/*
DeleteIpamIPNotFound IP address not found

swagger:response deleteIpamIpNotFound
*/
type DeleteIpamIPNotFound struct {
}

// NewDeleteIpamIPNotFound creates DeleteIpamIPNotFound with default headers values
func NewDeleteIpamIPNotFound() *DeleteIpamIPNotFound {

	return &DeleteIpamIPNotFound{}
}

// WriteResponse to the client
func (o *DeleteIpamIPNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteIpamIPInternalServerErrorCode is the HTTP code returned for type DeleteIpamIPInternalServerError
const DeleteIpamIPInternalServerErrorCode int = 500

/*
DeleteIpamIPInternalServerError IP address release failed

swagger:response deleteIpamIpInternalServerError
*/
type DeleteIpamIPInternalServerError struct {
}

// NewDeleteIpamIPInternalServerError creates DeleteIpamIPInternalServerError with default headers values
func NewDeleteIpamIPInternalServerError() *DeleteIpamIPInternalServerError {

	return &DeleteIpamIPInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteIpamIPInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
