// Code generated by go-swagger; DO NOT EDIT.

package ipam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/21kyu/simple-cni-plugin/api/models"
)

// PostIpamCreatedCode is the HTTP code returned for type PostIpamCreated
const PostIpamCreatedCode int = 201

/*
PostIpamCreated IP address allocated

swagger:response postIpamCreated
*/
type PostIpamCreated struct {

	/*
	  In: Body
	*/
	Payload *models.IpamResponse `json:"body,omitempty"`
}

// NewPostIpamCreated creates PostIpamCreated with default headers values
func NewPostIpamCreated() *PostIpamCreated {

	return &PostIpamCreated{}
}

// WithPayload adds the payload to the post ipam created response
func (o *PostIpamCreated) WithPayload(payload *models.IpamResponse) *PostIpamCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post ipam created response
func (o *PostIpamCreated) SetPayload(payload *models.IpamResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostIpamCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
